stages:
  - build
  - test

image: openjdk:21-slim

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:
  stage: build
  only:
    - main
    - test-branch
  script:
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - chmod +x gradlew
    - ./gradlew test
  only:
    - main
    - test-branch