stages:
  - build
  - test
  - deploy

image: openjdk:17-slim # Use a Docker image that includes Java

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle" # Cache Gradle dependencies locally

build:
  stage: build
  only:
    - main
    - feature/cli
  script:
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./gradlew test
  only:
    - main
    - feature/cli

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - scp build/libs/*.jar user@your-server:/path/to/deploy/
    - ssh user@your-server 'systemctl restart your-service'
  only:
    - main
    - feature/cli