stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - main
    - feature
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  only:
    - main
    - feature
  script:
    - ./gradlew test

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to production..."
    - scp build/libs/*.jar user@your-server:/path/to/deploy/
    - ssh user@your-server 'systemctl restart your-service'
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

