stages:
  - build
  - test
  - deploy

image: openjdk:17-slim # Use a Docker image that includes Java

variables:
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk" # Set JAVA_HOME for Java 17
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:
  stage: build
  only:
    - main
    - feature/cli
  script:
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  only:
    - main
    - feature/cli
  script:
    - ./gradlew test

deploy:
  stage: deploy
  only:
    - main
    - feature/cli
  script:
    - echo "Deploying to production..."
    - scp build/libs/*.jar user@your-server:/path/to/deploy/
    - ssh user@your-server 'systemctl restart your-service'
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

