stages:
  - build
  - test

image: openjdk:17-slim # Use a Docker image that includes Java

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle" # Cache Gradle dependencies locally

build:
  stage: build
  only:
    - main
    - feature/cli
  script:
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - chmod +x gradlew
    - ./gradlew test
  only:
    - main
    - feature/cli