name: CI Pipeline

on:
  push:
    branches:
      - main
      - test-branch
      - CI
  pull_request:
    branches:
      - main
      - test-branch

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-slim

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: database
          POSTGRES_USER: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.SPRING_DATASOURCE_USERNAME }} -d database"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL to be Ready
        run: sleep 10

      - name: Set Executable Permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/database
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      - name: Run Tests
        run: ./gradlew test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/database
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
