name: CI Pipeline

on:
  push:
    branches:
      - main
      - test-branch
      - CI
  pull_request:
    branches:
      - main
      - test-branch
      - CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-slim
    env:
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Executable Permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: build/libs/*.jar
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: openjdk:21-slim
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Executable Permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test
